;这是《PC数据恢复》的微信扫码付款配置文件


[窗口设置]
标题 = 开通VIP，立刻解锁VIP功能，恢复数据


[限时优惠]
产品文字行号 = 2;3
;文字属性 = Microsoft YaHei;10;粗体;#ff0000


[点击这里]
URL = https://www.disktool.cn/recovery/adr-windows.html
;文字 = 
;文字属性 = Microsoft YaHei;6;;#333333


[支付问题]
URL = https://www.disktool.cn/recovery/adr-windows.html
;文字 = 
;文字属性 = Microsoft YaHei;6;;#333333


[开具发票]
URL = https://www.disktool.cn/recovery/adr-windows.html
;文字 = 
;文字属性 = Microsoft YaHei;6;;#333333


[产品一]
文字行数 = 5
文字1 = 终身版;Microsoft YaHei;20;粗体;n=#333333 h=#333333 c=#333333;水平居中 y=24
文字2 = ¥;Microsoft YaHei;16;粗体;n=#F5AB18 h=#FF8C17 c=#FF8C17;x=44 y=88
文字3 = 169;Microsoft YaHei;38;粗体;n=#F5AB18 h=#FF8C17 c=#FF8C17;水平居中 y=66
文字4 = ¥198;Microsoft YaHei;13;删除线;n=#988F85 h=#988F85 c=#988F85;水平居中 y=126
文字5 = 终身使用，免费更新;Microsoft YaHei;13;;n=#988F85 h=#988F85 c=#988F85;水平居中 y=155


[产品一特性]
行首图标X = 482
第一行图标Y = 72
第一行文字Y = 67
图标文字间距 = 14
行距 = 28
字体属性 = Microsoft YaHei;12;;#4D4944

特性文字行数 = 13
特性1 = 设备数：5台
特性2 = 支持可恢复文件预览
特性3 = 支持边扫描边查看文件
特性4 = 支持快速扫描恢复
特性5 = 支持Windows个人系统
特性6 = 恢复文件类型无限制
特性7 = 高级技术支持
特性8 = 恢复数据量无限制
特性9 = 恢复单个文件大小无限制
特性10 = 支持Windows Sever系统
特性11 = 支持商业使用
特性12 = 支持远程协助
特性13 = 终身使用&升级



[产品二]
文字行数 = 5
文字1 = 1年版;Microsoft YaHei;20;粗体;n=#333333 h=#333333 c=#333333;水平居中 y=24
文字2 = ¥;Microsoft YaHei;16;粗体;n=#F5AB18 h=#FF8C17 c=#FF8C17;x=53 y=88
文字3 = 98;Microsoft YaHei;38;粗体;n=#F5AB18 h=#FF8C17 c=#FF8C17;水平居中 y=66
文字4 = ¥128;Microsoft YaHei;13;删除线;n=#988F85 h=#988F85 c=#988F85;水平居中 y=126
文字5 = 仅支持1年;Microsoft YaHei;13;;n=#988F85 h=#988F85 c=#988F85;水平居中 y=155


[产品二特性]
行首图标X = 482
第一行图标Y = 72
第一行文字Y = 67
图标文字间距 = 14
行距 = 28
字体属性 = Microsoft YaHei;12;;#4D4944

特性文字行数 = 13
特性1 = 设备数：2台
特性2 = 支持可恢复文件预览
特性3 = 支持边扫描边查看文件
特性4 = 支持快速扫描恢复
特性5 = 支持Windows个人系统
特性6 = 恢复文件类型无限制
特性7 = 高级技术支持
特性8 = 恢复数据量无限制
特性9 = 恢复单个文件大小无限制
特性10 = 支持Windows Sever系统
特性11 = 支持商业使用
特性12 = 支持远程协助
特性13 = 终身使用&升级
